substitutions:
  name: s31-1
  friendly_name: Sonoff-31-1

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

esp8266:
  board: esp01_1m

# Enable logging (Sonoff S31 flashed with ESPHome stopped displaying consumption data, disable logging to fix.)
logger:
  baud_rate: 0 # (UART logging interferes with cse7766)
  logs:
    sensor: DEBUG # (Overide any global setting, to VERBOSE will spamming the cse7766 sensors)

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key07

ota:
  - platform: esphome
    password: !secret ota_password05

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${friendly_name}
    password: !secret wifi_hotspot_password
  # Status LED
  on_connect:
    - light.turn_on: StatusLED
  on_disconnect:
    - light.turn_off: StatusLED

captive_portal:

# Enable Web server.
web_server:
  port: 80

# Device Specific Config
uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN
  stop_bits: 1
  data_bits: 8

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: Sonoff S31 Button
    on_press:
      - switch.toggle: relay
  - platform: status
    name: Sonoff S31 Status

sensor:
  - platform: wifi_signal
    name: Sonoff S31 WiFi Signal
    update_interval: 60s
  - platform: cse7766
    current:
      name: Sonoff S31 Current
      accuracy_decimals: 2
      filters:
        - throttle_average: 60s
    voltage:
      name: Sonoff S31 Voltage
      accuracy_decimals: 2
      filters:
        - throttle_average: 60s
    power:
      name: Sonoff S31 Power
      accuracy_decimals: 2
      id: my_power
      filters:
        - throttle_average: 60s
    energy:
      name: Sonoff S31 Energy
      accuracy_decimals: 2
      filters:
        - throttle: 60s
    apparent_power: #(only available with version 2024.3.0 or greater)
      name: Sonoff S31 Apparent Power
      filters:
        - throttle_average: 60s
    power_factor: #(only available with version 2024.3.0 or greater)
      name: Sonoff S31 Power Factor
      accuracy_decimals: 2
      filters:
        - throttle_average: 60s

  - platform: total_daily_energy #(Optional, not specific to cse7766)
    name: Sonoff S31 Daily Energy
    power_id: my_power
    accuracy_decimals: 2

switch:
  - platform: gpio
    name: Sonoff S31 Relay
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_ON

time:
  - platform: sntp #(required for total_daily_energy)
    id: my_time

#status_led:
#  pin:
#    number: GPIO13
#    inverted: True

light:
  - platform: status_led
    name: StatusLED
    id: StatusLED
    pin:
      number: GPIO13
      inverted: True
